_target_: control.algorithms.ppo.PPO

learning_rate: 3e-4
n_steps: 1000
batch_size: 5000
n_epochs: 10
gamma: 0.999
gae_lambda: 0.95
clip_range: 0.2
ent_coef: 0.005
vf_coef: 0.5
max_grad_norm: 0.5
policy_type: MlpPolicy
activation_fn: relu
log_std_init: -2.0

net_arch:
  pi: [64, 64, 64]
  vf: [64, 64, 64]

# Inject AsymmetricPolicy as custom features_extractor_class
policy_kwargs:
  features_extractor_class:
    _target_: control.policies.asymmetric_policy.AsymmetricPolicy
  share_features_extractor: false
