"""Baseline promotion: verify, create PR body, update state after merge."""

from __future__ import annotations

import shutil
from dataclasses import dataclass
from pathlib import Path

from autoresearch.archive.map_elites import MapElitesArchive
from autoresearch.archive.serialization import save_archive, load_archive
from autoresearch.descriptors.compute import DescriptorVector
from autoresearch.tree.serialization import save_tree, load_tree


@dataclass
class PromotionCandidate:
    hypothesis_id: str
    wandb_run_id: str
    fitness: float
    descriptors: DescriptorVector
    branch: str
    git_commit: str


@dataclass
class PromotionResult:
    verified: bool
    reason: str


def verify_promotion_candidate(
    candidate: PromotionCandidate,
    archive: MapElitesArchive,
) -> PromotionResult:
    found = False
    for cell, entry in archive.occupied_cells().items():
        if entry.hypothesis_id == candidate.hypothesis_id:
            found = True
            if entry.status != "approved":
                return PromotionResult(
                    verified=False,
                    reason=f"Candidate {candidate.hypothesis_id} has status '{entry.status}', must be 'approved' for promotion",
                )
            break
    if not found:
        return PromotionResult(verified=False, reason=f"Candidate {candidate.hypothesis_id} not found in archive")
    return PromotionResult(verified=True, reason="Candidate verified for promotion")


def generate_pr_body(
    candidate: PromotionCandidate,
    old_baseline_fitness: float | None,
    wandb_url: str,
) -> str:
    improvement = ""
    if old_baseline_fitness is not None:
        delta = old_baseline_fitness - candidate.fitness
        pct = (delta / old_baseline_fitness) * 100 if old_baseline_fitness > 0 else 0
        improvement = f"\n**Improvement:** {delta:.2f}s ({pct:.1f}% better lap time)"

    desc = candidate.descriptors
    return f"""## Summary

Promote experiment `{candidate.hypothesis_id}` to new baseline.

**Fitness (lap time):** {candidate.fitness:.3f}s (old baseline: {old_baseline_fitness or 'N/A'}){improvement}

## Behavioral Profile

| Descriptor | Value |
|-----------|-------|
| Actuator Utilization | {desc.actuator_utilization:.3f} |
| Control Smoothness | {desc.control_smoothness:.3f} |
| Aero Regime Index | {desc.aero_regime:.3f} |

## Links

- W&B Run: {wandb_url}
- Branch: `{candidate.branch}`
- Commit: `{candidate.git_commit}`

---
Generated by auto-research system
"""


def update_state_after_promotion(
    state_dir: Path | str,
    hypothesis_id: str,
    merge_commit: str,
    new_baseline_name: str,
    promoter: str,
) -> None:
    state_dir = Path(state_dir)

    # Determine version number
    existing_versions = list(state_dir.glob("archive_v*.json"))
    version = len(existing_versions) + 1

    # Archive current grid
    current_archive_path = state_dir / "archive.json"
    archived_path = state_dir / f"archive_v{version}.json"
    shutil.copy2(current_archive_path, archived_path)

    # Create fresh archive
    fresh_archive = MapElitesArchive()
    save_archive(fresh_archive, current_archive_path)

    # Update research tree via public API
    tree = load_tree(state_dir / "tree.json")
    tree.promote_baseline(
        new_baseline_id=new_baseline_name,
        git_commit=merge_commit,
        description=f"Promoted from {hypothesis_id}",
        promoter=promoter,
    )
    save_tree(tree, state_dir / "tree.json")
